[package]
name = "acousticdi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dasp = { version = "0.11.0", features = ["signal"] }
hound = "3.4.0"
once_cell = "1.18.0"
